### ISSUE TITLE
sirajcoin Balance

### ISSUE THREAD

**Issue by zzzhacker** [llSourcell/sirajcoin#13]
sirajcoin balance
module.js:689
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/usr/lib/node_modules/sirajcoin/node_modules/ed25519-supercop/build/Release/supercop.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 59. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:689:18)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/sirajcoin/node_modules/ed25519-supercop/index.js:1:78)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)

**Comment by ravindrabarthwal** [comment]
The error is saying that you have compiled the sirajcoin package on different nodejs version `NODE_MODULE_VERSION 48` and now you are accessing using different nodejs version `NODE_MODULE_VERSION 59`
It is because you have updated the version of nodejs. You can do two things
Solution 1. reinstall the previous version of nodejs in which you installed sirajcoin package
Solution 2. reinstall the sirajcoin package on the updated nodejs version.

**Comment by zzzhacker** [comment]
I reinstall the sirajcoin after update nodejs but it shows this error

**Comment by danielsan** [comment]
@zzzhacker could you please help us with reproducing the issue?

- What version of node.js are you using?
- What operating system are you using?
- What are the commands you are running? ALL OF THEM, 1 by 1, please.

**Comment by zzzhacker** [comment]
Ohk I figure out the things and now its working.
@danielsan  i update it but  change the node version after restart now it works fine
